<a href="https://colab.research.google.com/github/asrarbhat/machineleanring/blob/main/k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

k means clustering

In [2]:
import numpy as np


In [3]:
input=np.array([[1,2,3],
               [3,4,4],
               [5,6,5],
                [4,4,6]
               ])

In [4]:
input.shape

(4, 3)

In [5]:
#hyperparameter
no_of_clusters=4
clusters=input[:no_of_clusters+1,:].reshape((no_of_clusters,1,input.shape[1]))
clusters

array([[[1, 2, 3]],

       [[3, 4, 4]],

       [[5, 6, 5]],

       [[4, 4, 6]]])

In [6]:
#learning
no_of_iterations=100;
def distances(input,clusters):
    distance=np.float_power(np.sum(np.power((clusters-input),2),axis=2),0.5)
    return distance
distances(input,clusters)








array([[0.        , 3.        , 6.        , 4.69041576],
       [3.        , 0.        , 3.        , 2.23606798],
       [6.        , 3.        , 0.        , 2.44948974],
       [4.69041576, 2.23606798, 2.44948974, 0.        ]])

In [7]:
for i in range(2):
    distance_matrix=distances(input,clusters)
    print(distance_matrix)
    min=np.min(distance_matrix,axis=0)
    print(min)
    distance_matrix-=min
    print(distance_matrix)
    nearby_matrix=distance_matrix==0.0
    print(nearby_matrix)
    nearby=nearby_matrix.reshape((no_of_clusters,input.shape[0],1))
    print(nearby)
    temporary=nearby*input
    print(temporary)
    new_cluster=(np.sum(temporary,axis=1)/(np.sum(temporary!=0,axis=1)+1))
    print(new_cluster)
    clusters=new_cluster.reshape(clusters.shape)

[[0.         3.         6.         4.69041576]
 [3.         0.         3.         2.23606798]
 [6.         3.         0.         2.44948974]
 [4.69041576 2.23606798 2.44948974 0.        ]]
[0. 0. 0. 0.]
[[0.         3.         6.         4.69041576]
 [3.         0.         3.         2.23606798]
 [6.         3.         0.         2.44948974]
 [4.69041576 2.23606798 2.44948974 0.        ]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[[ True]
  [False]
  [False]
  [False]]

 [[False]
  [ True]
  [False]
  [False]]

 [[False]
  [False]
  [ True]
  [False]]

 [[False]
  [False]
  [False]
  [ True]]]
[[[1 2 3]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [3 4 4]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [5 6 5]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [4 4 6]]]
[[0.5 1.  1.5]
 [1.5 2.  2. ]
 [2.5 3.  2.5]
 [2.  2.  3. ]]
[[1.87082869 4.63680925 7.58287544 6.44204936]
 [1.11803399 3.20156212 6.10327781 5.12347538]
 [1.8708

In [ ]:
input,clusters