In [ ]:
import numpy as np

when using asarray changes reflect in original numpy array and when using array then changes won't refect,when building from list,changes won't reflect

In [ ]:
l=[1,2,3,4]
arr=np.asarray(l)
arr

array([1, 2, 3, 4])

In [ ]:
arr1=np.asarray(arr[:2])
arr1+=1
arr1

array([2, 3])

In [ ]:
arr

array([2, 3, 3, 4])

In [ ]:
arr3=np.array(arr[:2])
arr3+=1
arr3

array([3, 4])

In [ ]:
arr

array([2, 3, 3, 4])

In [ ]:
l=[
   [1,2,3],
   [4,5,6]
]
arr=np.array(l)
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.ndim

2

In [ ]:
np.sum(arr,axis=0)
np.max(arr,axis=1)
arr>3

array([[False, False, False],
       [ True,  True,  True]])

In [ ]:
arr1=np.ones(arr.shape)
arr1=arr1.astype('int64')
arr1,arr

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [ ]:
np.hstack([arr,arr1])
np.vstack([arr,arr1])
arr+arr1
arr+2
arr[0,1]=77
arr
ranger=np.arange(1,100,2).reshape(5,10)
ranger

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [ ]:
are=ranger[1:3,1:4].copy()
are+=100
are
ranger

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [ ]:
np.linspace(1,20,13)

array([ 1.        ,  2.58333333,  4.16666667,  5.75      ,  7.33333333,
        8.91666667, 10.5       , 12.08333333, 13.66666667, 15.25      ,
       16.83333333, 18.41666667, 20.        ])

In [ ]:
arr7=arr[0,:].copy()
np.append(arr7,[1,2,3])
arr
np.append(arr,[[1,2,3]])

arr

array([[ 1, 77,  3],
       [ 4,  5,  6]])

In [ ]:
np.save('first.npy',arr)

In [ ]:
arrays=np.load("first.npy")

In [ ]:
arrays

array([[ 1, 77,  3],
       [ 4,  5,  6]])

In [ ]:
arr1
np.savez_compressed("second.npz",arr,arr1)

In [ ]:
arrays=np.load("second.npz")
arrays.files
arrays['arr_1']

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr=np.genfromtxt("life.csv",delimiter=',',skip_header=1,usecols=[1,2])
arr

array([[1., 5.],
       [2., 6.],
       [3., 7.],
       [4., 8.]])